package com.wzsport.model;

public class AreaActivityDataStatistic {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_area_activity_data_statistic.id
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_area_activity_data_statistic.student_id
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    private Long studentId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_area_activity_data_statistic.activity_id
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    private Long activityId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_area_activity_data_statistic.location_total_count
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    private Integer locationTotalCount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_area_activity_data_statistic.location_against
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    private Integer locationAgainst;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_area_activity_data_statistic.id
     * @return  the value of wzsport_area_activity_data_statistic.id
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_area_activity_data_statistic.id
     * @param id  the value for wzsport_area_activity_data_statistic.id
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_area_activity_data_statistic.student_id
     * @return  the value of wzsport_area_activity_data_statistic.student_id
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_area_activity_data_statistic.student_id
     * @param studentId  the value for wzsport_area_activity_data_statistic.student_id
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_area_activity_data_statistic.activity_id
     * @return  the value of wzsport_area_activity_data_statistic.activity_id
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_area_activity_data_statistic.activity_id
     * @param activityId  the value for wzsport_area_activity_data_statistic.activity_id
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_area_activity_data_statistic.location_total_count
     * @return  the value of wzsport_area_activity_data_statistic.location_total_count
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    public Integer getLocationTotalCount() {
        return locationTotalCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_area_activity_data_statistic.location_total_count
     * @param locationTotalCount  the value for wzsport_area_activity_data_statistic.location_total_count
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    public void setLocationTotalCount(Integer locationTotalCount) {
        this.locationTotalCount = locationTotalCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_area_activity_data_statistic.location_against
     * @return  the value of wzsport_area_activity_data_statistic.location_against
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    public Integer getLocationAgainst() {
        return locationAgainst;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_area_activity_data_statistic.location_against
     * @param locationAgainst  the value for wzsport_area_activity_data_statistic.location_against
     * @mbg.generated  Sat Nov 18 12:05:52 CST 2017
     */
    public void setLocationAgainst(Integer locationAgainst) {
        this.locationAgainst = locationAgainst;
    }

    private FixLocationOutdoorSportPoint location;

    public FixLocationOutdoorSportPoint getLocation() {
        return location;
    }

    public void setLocation(FixLocationOutdoorSportPoint location) {
        this.location = location;
    }
    
}