package com.wzsport.model;

public class SportsCourse {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.id
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.university_id
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private Long universityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.school_year
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private String schoolYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.term
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private Integer term;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.subject_number
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private String subjectNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.course_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private String courseName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.teacher_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private String teacherName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.course_time
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private String courseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.student_no
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private String studentNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.student_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private String studentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.is_man
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private Boolean isMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.major_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private String majorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_sports_course.college_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	private String collegeName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.id
	 * @return  the value of wzsport_sports_course.id
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.id
	 * @param id  the value for wzsport_sports_course.id
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.university_id
	 * @return  the value of wzsport_sports_course.university_id
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public Long getUniversityId() {
		return universityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.university_id
	 * @param universityId  the value for wzsport_sports_course.university_id
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setUniversityId(Long universityId) {
		this.universityId = universityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.school_year
	 * @return  the value of wzsport_sports_course.school_year
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public String getSchoolYear() {
		return schoolYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.school_year
	 * @param schoolYear  the value for wzsport_sports_course.school_year
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setSchoolYear(String schoolYear) {
		this.schoolYear = schoolYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.term
	 * @return  the value of wzsport_sports_course.term
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public Integer getTerm() {
		return term;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.term
	 * @param term  the value for wzsport_sports_course.term
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setTerm(Integer term) {
		this.term = term;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.subject_number
	 * @return  the value of wzsport_sports_course.subject_number
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public String getSubjectNumber() {
		return subjectNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.subject_number
	 * @param subjectNumber  the value for wzsport_sports_course.subject_number
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setSubjectNumber(String subjectNumber) {
		this.subjectNumber = subjectNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.course_name
	 * @return  the value of wzsport_sports_course.course_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public String getCourseName() {
		return courseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.course_name
	 * @param courseName  the value for wzsport_sports_course.course_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.teacher_name
	 * @return  the value of wzsport_sports_course.teacher_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public String getTeacherName() {
		return teacherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.teacher_name
	 * @param teacherName  the value for wzsport_sports_course.teacher_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.course_time
	 * @return  the value of wzsport_sports_course.course_time
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public String getCourseTime() {
		return courseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.course_time
	 * @param courseTime  the value for wzsport_sports_course.course_time
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setCourseTime(String courseTime) {
		this.courseTime = courseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.student_no
	 * @return  the value of wzsport_sports_course.student_no
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public String getStudentNo() {
		return studentNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.student_no
	 * @param studentNo  the value for wzsport_sports_course.student_no
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.student_name
	 * @return  the value of wzsport_sports_course.student_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public String getStudentName() {
		return studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.student_name
	 * @param studentName  the value for wzsport_sports_course.student_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.is_man
	 * @return  the value of wzsport_sports_course.is_man
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public Boolean getIsMan() {
		return isMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.is_man
	 * @param isMan  the value for wzsport_sports_course.is_man
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setIsMan(Boolean isMan) {
		this.isMan = isMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.major_name
	 * @return  the value of wzsport_sports_course.major_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public String getMajorName() {
		return majorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.major_name
	 * @param majorName  the value for wzsport_sports_course.major_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_sports_course.college_name
	 * @return  the value of wzsport_sports_course.college_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public String getCollegeName() {
		return collegeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_sports_course.college_name
	 * @param collegeName  the value for wzsport_sports_course.college_name
	 * @mbg.generated  Mon Nov 20 14:03:21 CST 2017
	 */
	public void setCollegeName(String collegeName) {
		this.collegeName = collegeName;
	}
}