package com.wzsport.model;

public class StudentUserView {
	private int cardNum;
	
	
	public int getCardNum() {
		return cardNum;
	}

	public void setCardNum(int cardNum) {
		this.cardNum = cardNum;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_user_view.class_name
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	private String className;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_user_view.univetsity_id
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	private Long univetsityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_user_view.user_type
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	private Byte userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_user_view.open_id
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_user_view.student_no
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	private String studentNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_user_view.is_man
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	private Boolean isMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_user_view.student_name
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	private String studentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_user_view.class_id
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	private Long classId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_user_view.class_name
	 * @return  the value of wzsport_student_user_view.class_name
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public String getClassName() {
		return className;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_user_view.class_name
	 * @param className  the value for wzsport_student_user_view.class_name
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public void setClassName(String className) {
		this.className = className;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_user_view.univetsity_id
	 * @return  the value of wzsport_student_user_view.univetsity_id
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public Long getUnivetsityId() {
		return univetsityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_user_view.univetsity_id
	 * @param univetsityId  the value for wzsport_student_user_view.univetsity_id
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public void setUnivetsityId(Long univetsityId) {
		this.univetsityId = univetsityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_user_view.user_type
	 * @return  the value of wzsport_student_user_view.user_type
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public Byte getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_user_view.user_type
	 * @param userType  the value for wzsport_student_user_view.user_type
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public void setUserType(Byte userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_user_view.open_id
	 * @return  the value of wzsport_student_user_view.open_id
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_user_view.open_id
	 * @param openId  the value for wzsport_student_user_view.open_id
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_user_view.student_no
	 * @return  the value of wzsport_student_user_view.student_no
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public String getStudentNo() {
		return studentNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_user_view.student_no
	 * @param studentNo  the value for wzsport_student_user_view.student_no
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_user_view.is_man
	 * @return  the value of wzsport_student_user_view.is_man
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public Boolean getIsMan() {
		return isMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_user_view.is_man
	 * @param isMan  the value for wzsport_student_user_view.is_man
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public void setIsMan(Boolean isMan) {
		this.isMan = isMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_user_view.student_name
	 * @return  the value of wzsport_student_user_view.student_name
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public String getStudentName() {
		return studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_user_view.student_name
	 * @param studentName  the value for wzsport_student_user_view.student_name
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_user_view.class_id
	 * @return  the value of wzsport_student_user_view.class_id
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public Long getClassId() {
		return classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_user_view.class_id
	 * @param classId  the value for wzsport_student_user_view.class_id
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	public void setClassId(Long classId) {
		this.classId = classId;
	}
}