package com.wzsport.model;

import java.util.Date;

public class StudentSportConsumeStatistic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.user_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.student_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long studentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.kcal_consumed
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long kcalConsumed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.cost_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long costTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.class_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long classId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.university_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long universityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.student_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String studentNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.is_man
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Boolean isMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.avatar_url
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String avatarUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.sport_date
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Date sportDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.id
	 * @return  the value of wzsport_student_sport_consume_statistic.id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.id
	 * @param id  the value for wzsport_student_sport_consume_statistic.id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.user_id
	 * @return  the value of wzsport_student_sport_consume_statistic.user_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.user_id
	 * @param userId  the value for wzsport_student_sport_consume_statistic.user_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.student_id
	 * @return  the value of wzsport_student_sport_consume_statistic.student_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.student_id
	 * @param studentId  the value for wzsport_student_sport_consume_statistic.student_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setStudentId(Long studentId) {
		this.studentId = studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.kcal_consumed
	 * @return  the value of wzsport_student_sport_consume_statistic.kcal_consumed
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getKcalConsumed() {
		return kcalConsumed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.kcal_consumed
	 * @param kcalConsumed  the value for wzsport_student_sport_consume_statistic.kcal_consumed
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setKcalConsumed(Long kcalConsumed) {
		this.kcalConsumed = kcalConsumed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.cost_time
	 * @return  the value of wzsport_student_sport_consume_statistic.cost_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getCostTime() {
		return costTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.cost_time
	 * @param costTime  the value for wzsport_student_sport_consume_statistic.cost_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setCostTime(Long costTime) {
		this.costTime = costTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.class_id
	 * @return  the value of wzsport_student_sport_consume_statistic.class_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getClassId() {
		return classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.class_id
	 * @param classId  the value for wzsport_student_sport_consume_statistic.class_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setClassId(Long classId) {
		this.classId = classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.university_id
	 * @return  the value of wzsport_student_sport_consume_statistic.university_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getUniversityId() {
		return universityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.university_id
	 * @param universityId  the value for wzsport_student_sport_consume_statistic.university_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setUniversityId(Long universityId) {
		this.universityId = universityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.student_no
	 * @return  the value of wzsport_student_sport_consume_statistic.student_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getStudentNo() {
		return studentNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.student_no
	 * @param studentNo  the value for wzsport_student_sport_consume_statistic.student_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.is_man
	 * @return  the value of wzsport_student_sport_consume_statistic.is_man
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Boolean getIsMan() {
		return isMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.is_man
	 * @param isMan  the value for wzsport_student_sport_consume_statistic.is_man
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setIsMan(Boolean isMan) {
		this.isMan = isMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.name
	 * @return  the value of wzsport_student_sport_consume_statistic.name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.name
	 * @param name  the value for wzsport_student_sport_consume_statistic.name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.avatar_url
	 * @return  the value of wzsport_student_sport_consume_statistic.avatar_url
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getAvatarUrl() {
		return avatarUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.avatar_url
	 * @param avatarUrl  the value for wzsport_student_sport_consume_statistic.avatar_url
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.sport_date
	 * @return  the value of wzsport_student_sport_consume_statistic.sport_date
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Date getSportDate() {
		return sportDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.sport_date
	 * @param sportDate  the value for wzsport_student_sport_consume_statistic.sport_date
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setSportDate(Date sportDate) {
		this.sportDate = sportDate;
	}
}