package com.wzsport.model;

import java.util.Date;

public class StudentCoursePhysicalTest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.university_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long universityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.college_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String collegeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.grade_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long gradeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.class_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long classNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.class_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String className;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.student_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String studentNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.nationality_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long nationalityNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.nationality_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String nationalityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.student_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String studentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.is_man
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Boolean isMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.birthday
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.home_address
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String homeAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.height
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Double height;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.weight
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Double weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.vital_capacity
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long vitalCapacity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.fifty_run_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Double fiftyRunTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.standing_long_jump
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Integer standingLongJump;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.sit_and_reach
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Double sitAndReach;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.eight_hundred_run_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Double eightHundredRunTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.one_thousand_run_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Double oneThousandRunTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.one_minute_sit_up
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Integer oneMinuteSitUp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.pull_up
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Integer pullUp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.is_tested
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Boolean isTested;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.is_free_test
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Boolean isFreeTest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.total_score
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Double totalScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.school_year
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String schoolYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.term
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Integer term;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.course_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String courseName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.teacher_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String teacherName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.course_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String courseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.major_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String majorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.is_pass
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Boolean isPass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sports_course_physical_test_view.id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.university_id
	 * @return  the value of wzsport_student_sports_course_physical_test_view.university_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getUniversityId() {
		return universityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.university_id
	 * @param universityId  the value for wzsport_student_sports_course_physical_test_view.university_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setUniversityId(Long universityId) {
		this.universityId = universityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.college_name
	 * @return  the value of wzsport_student_sports_course_physical_test_view.college_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getCollegeName() {
		return collegeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.college_name
	 * @param collegeName  the value for wzsport_student_sports_course_physical_test_view.college_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setCollegeName(String collegeName) {
		this.collegeName = collegeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.grade_no
	 * @return  the value of wzsport_student_sports_course_physical_test_view.grade_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getGradeNo() {
		return gradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.grade_no
	 * @param gradeNo  the value for wzsport_student_sports_course_physical_test_view.grade_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setGradeNo(Long gradeNo) {
		this.gradeNo = gradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.class_no
	 * @return  the value of wzsport_student_sports_course_physical_test_view.class_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getClassNo() {
		return classNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.class_no
	 * @param classNo  the value for wzsport_student_sports_course_physical_test_view.class_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setClassNo(Long classNo) {
		this.classNo = classNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.class_name
	 * @return  the value of wzsport_student_sports_course_physical_test_view.class_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getClassName() {
		return className;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.class_name
	 * @param className  the value for wzsport_student_sports_course_physical_test_view.class_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setClassName(String className) {
		this.className = className;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.student_no
	 * @return  the value of wzsport_student_sports_course_physical_test_view.student_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getStudentNo() {
		return studentNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.student_no
	 * @param studentNo  the value for wzsport_student_sports_course_physical_test_view.student_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.nationality_no
	 * @return  the value of wzsport_student_sports_course_physical_test_view.nationality_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getNationalityNo() {
		return nationalityNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.nationality_no
	 * @param nationalityNo  the value for wzsport_student_sports_course_physical_test_view.nationality_no
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setNationalityNo(Long nationalityNo) {
		this.nationalityNo = nationalityNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.nationality_name
	 * @return  the value of wzsport_student_sports_course_physical_test_view.nationality_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getNationalityName() {
		return nationalityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.nationality_name
	 * @param nationalityName  the value for wzsport_student_sports_course_physical_test_view.nationality_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setNationalityName(String nationalityName) {
		this.nationalityName = nationalityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.student_name
	 * @return  the value of wzsport_student_sports_course_physical_test_view.student_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getStudentName() {
		return studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.student_name
	 * @param studentName  the value for wzsport_student_sports_course_physical_test_view.student_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.is_man
	 * @return  the value of wzsport_student_sports_course_physical_test_view.is_man
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Boolean getIsMan() {
		return isMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.is_man
	 * @param isMan  the value for wzsport_student_sports_course_physical_test_view.is_man
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setIsMan(Boolean isMan) {
		this.isMan = isMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.birthday
	 * @return  the value of wzsport_student_sports_course_physical_test_view.birthday
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.birthday
	 * @param birthday  the value for wzsport_student_sports_course_physical_test_view.birthday
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.home_address
	 * @return  the value of wzsport_student_sports_course_physical_test_view.home_address
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getHomeAddress() {
		return homeAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.home_address
	 * @param homeAddress  the value for wzsport_student_sports_course_physical_test_view.home_address
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.height
	 * @return  the value of wzsport_student_sports_course_physical_test_view.height
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Double getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.height
	 * @param height  the value for wzsport_student_sports_course_physical_test_view.height
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setHeight(Double height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.weight
	 * @return  the value of wzsport_student_sports_course_physical_test_view.weight
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Double getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.weight
	 * @param weight  the value for wzsport_student_sports_course_physical_test_view.weight
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setWeight(Double weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.vital_capacity
	 * @return  the value of wzsport_student_sports_course_physical_test_view.vital_capacity
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getVitalCapacity() {
		return vitalCapacity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.vital_capacity
	 * @param vitalCapacity  the value for wzsport_student_sports_course_physical_test_view.vital_capacity
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setVitalCapacity(Long vitalCapacity) {
		this.vitalCapacity = vitalCapacity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.fifty_run_time
	 * @return  the value of wzsport_student_sports_course_physical_test_view.fifty_run_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Double getFiftyRunTime() {
		return fiftyRunTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.fifty_run_time
	 * @param fiftyRunTime  the value for wzsport_student_sports_course_physical_test_view.fifty_run_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setFiftyRunTime(Double fiftyRunTime) {
		this.fiftyRunTime = fiftyRunTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.standing_long_jump
	 * @return  the value of wzsport_student_sports_course_physical_test_view.standing_long_jump
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Integer getStandingLongJump() {
		return standingLongJump;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.standing_long_jump
	 * @param standingLongJump  the value for wzsport_student_sports_course_physical_test_view.standing_long_jump
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setStandingLongJump(Integer standingLongJump) {
		this.standingLongJump = standingLongJump;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.sit_and_reach
	 * @return  the value of wzsport_student_sports_course_physical_test_view.sit_and_reach
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Double getSitAndReach() {
		return sitAndReach;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.sit_and_reach
	 * @param sitAndReach  the value for wzsport_student_sports_course_physical_test_view.sit_and_reach
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setSitAndReach(Double sitAndReach) {
		this.sitAndReach = sitAndReach;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.eight_hundred_run_time
	 * @return  the value of wzsport_student_sports_course_physical_test_view.eight_hundred_run_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Double getEightHundredRunTime() {
		return eightHundredRunTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.eight_hundred_run_time
	 * @param eightHundredRunTime  the value for wzsport_student_sports_course_physical_test_view.eight_hundred_run_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setEightHundredRunTime(Double eightHundredRunTime) {
		this.eightHundredRunTime = eightHundredRunTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.one_thousand_run_time
	 * @return  the value of wzsport_student_sports_course_physical_test_view.one_thousand_run_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Double getOneThousandRunTime() {
		return oneThousandRunTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.one_thousand_run_time
	 * @param oneThousandRunTime  the value for wzsport_student_sports_course_physical_test_view.one_thousand_run_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setOneThousandRunTime(Double oneThousandRunTime) {
		this.oneThousandRunTime = oneThousandRunTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.one_minute_sit_up
	 * @return  the value of wzsport_student_sports_course_physical_test_view.one_minute_sit_up
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Integer getOneMinuteSitUp() {
		return oneMinuteSitUp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.one_minute_sit_up
	 * @param oneMinuteSitUp  the value for wzsport_student_sports_course_physical_test_view.one_minute_sit_up
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setOneMinuteSitUp(Integer oneMinuteSitUp) {
		this.oneMinuteSitUp = oneMinuteSitUp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.pull_up
	 * @return  the value of wzsport_student_sports_course_physical_test_view.pull_up
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Integer getPullUp() {
		return pullUp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.pull_up
	 * @param pullUp  the value for wzsport_student_sports_course_physical_test_view.pull_up
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setPullUp(Integer pullUp) {
		this.pullUp = pullUp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.is_tested
	 * @return  the value of wzsport_student_sports_course_physical_test_view.is_tested
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Boolean getIsTested() {
		return isTested;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.is_tested
	 * @param isTested  the value for wzsport_student_sports_course_physical_test_view.is_tested
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setIsTested(Boolean isTested) {
		this.isTested = isTested;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.is_free_test
	 * @return  the value of wzsport_student_sports_course_physical_test_view.is_free_test
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Boolean getIsFreeTest() {
		return isFreeTest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.is_free_test
	 * @param isFreeTest  the value for wzsport_student_sports_course_physical_test_view.is_free_test
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setIsFreeTest(Boolean isFreeTest) {
		this.isFreeTest = isFreeTest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.total_score
	 * @return  the value of wzsport_student_sports_course_physical_test_view.total_score
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Double getTotalScore() {
		return totalScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.total_score
	 * @param totalScore  the value for wzsport_student_sports_course_physical_test_view.total_score
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setTotalScore(Double totalScore) {
		this.totalScore = totalScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.school_year
	 * @return  the value of wzsport_student_sports_course_physical_test_view.school_year
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getSchoolYear() {
		return schoolYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.school_year
	 * @param schoolYear  the value for wzsport_student_sports_course_physical_test_view.school_year
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setSchoolYear(String schoolYear) {
		this.schoolYear = schoolYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.term
	 * @return  the value of wzsport_student_sports_course_physical_test_view.term
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Integer getTerm() {
		return term;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.term
	 * @param term  the value for wzsport_student_sports_course_physical_test_view.term
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setTerm(Integer term) {
		this.term = term;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.course_name
	 * @return  the value of wzsport_student_sports_course_physical_test_view.course_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getCourseName() {
		return courseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.course_name
	 * @param courseName  the value for wzsport_student_sports_course_physical_test_view.course_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.teacher_name
	 * @return  the value of wzsport_student_sports_course_physical_test_view.teacher_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getTeacherName() {
		return teacherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.teacher_name
	 * @param teacherName  the value for wzsport_student_sports_course_physical_test_view.teacher_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.course_time
	 * @return  the value of wzsport_student_sports_course_physical_test_view.course_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getCourseTime() {
		return courseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.course_time
	 * @param courseTime  the value for wzsport_student_sports_course_physical_test_view.course_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setCourseTime(String courseTime) {
		this.courseTime = courseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.major_name
	 * @return  the value of wzsport_student_sports_course_physical_test_view.major_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getMajorName() {
		return majorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.major_name
	 * @param majorName  the value for wzsport_student_sports_course_physical_test_view.major_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.is_pass
	 * @return  the value of wzsport_student_sports_course_physical_test_view.is_pass
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Boolean getIsPass() {
		return isPass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.is_pass
	 * @param isPass  the value for wzsport_student_sports_course_physical_test_view.is_pass
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setIsPass(Boolean isPass) {
		this.isPass = isPass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sports_course_physical_test_view.id
	 * @return  the value of wzsport_student_sports_course_physical_test_view.id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sports_course_physical_test_view.id
	 * @param id  the value for wzsport_student_sports_course_physical_test_view.id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}
}