package com.wzsport.model;

import java.util.Date;
import java.sql.Timestamp;

public class UpdatePhysicalTestRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_update_physical_test_record.id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_update_physical_test_record.physical_test_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long physicalTestId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_update_physical_test_record.alter_user_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Long alterUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_update_physical_test_record.alter_user_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String alterUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_update_physical_test_record.remarks
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_update_physical_test_record.alter_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Timestamp alterTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_update_physical_test_record.is_alter
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	private Boolean isAlter;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_update_physical_test_record.id
	 * @return  the value of wzsport_update_physical_test_record.id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_update_physical_test_record.id
	 * @param id  the value for wzsport_update_physical_test_record.id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_update_physical_test_record.physical_test_id
	 * @return  the value of wzsport_update_physical_test_record.physical_test_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getPhysicalTestId() {
		return physicalTestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_update_physical_test_record.physical_test_id
	 * @param physicalTestId  the value for wzsport_update_physical_test_record.physical_test_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setPhysicalTestId(Long physicalTestId) {
		this.physicalTestId = physicalTestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_update_physical_test_record.alter_user_id
	 * @return  the value of wzsport_update_physical_test_record.alter_user_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Long getAlterUserId() {
		return alterUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_update_physical_test_record.alter_user_id
	 * @param alterUserId  the value for wzsport_update_physical_test_record.alter_user_id
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setAlterUserId(Long alterUserId) {
		this.alterUserId = alterUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_update_physical_test_record.alter_user_name
	 * @return  the value of wzsport_update_physical_test_record.alter_user_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getAlterUserName() {
		return alterUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_update_physical_test_record.alter_user_name
	 * @param alterUserName  the value for wzsport_update_physical_test_record.alter_user_name
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setAlterUserName(String alterUserName) {
		this.alterUserName = alterUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_update_physical_test_record.remarks
	 * @return  the value of wzsport_update_physical_test_record.remarks
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_update_physical_test_record.remarks
	 * @param remarks  the value for wzsport_update_physical_test_record.remarks
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_update_physical_test_record.alter_time
	 * @return  the value of wzsport_update_physical_test_record.alter_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Timestamp getAlterTime() {
		return alterTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_update_physical_test_record.alter_time
	 * @param alterTime  the value for wzsport_update_physical_test_record.alter_time
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setAlterTime(Timestamp alterTime) {
		this.alterTime = alterTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_update_physical_test_record.is_alter
	 * @return  the value of wzsport_update_physical_test_record.is_alter
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public Boolean getIsAlter() {
		return isAlter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_update_physical_test_record.is_alter
	 * @param isAlter  the value for wzsport_update_physical_test_record.is_alter
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	public void setIsAlter(Boolean isAlter) {
		this.isAlter = isAlter;
	}
}