package com.wzsport.mapper;

import com.wzsport.model.PhysicalTest;
import com.wzsport.model.PhysicalTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface PhysicalTestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_physical_test
	 * @mbg.generated  Sun Nov 26 10:54:40 CST 2017
	 */
	long countByExample(PhysicalTestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_physical_test
	 * @mbg.generated  Sun Nov 26 10:54:40 CST 2017
	 */
	int deleteByExample(PhysicalTestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_physical_test
	 * @mbg.generated  Sun Nov 26 10:54:40 CST 2017
	 */
	@Delete({ "delete from wzsport_physical_test", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_physical_test
	 * @mbg.generated  Sun Nov 26 10:54:40 CST 2017
	 */
	@Insert({ "insert into wzsport_physical_test (university_id, school_year, ", "term, college_name, grade_no, ",
			"class_no, class_name, ", "student_no, nationality_no, ", "nationality_name, student_name, ",
			"is_man, birthday, home_address, ", "height, weight, ", "bmi, bmi_score, ", "bmi_grade, vital_capacity, ",
			"standing_long_jump, sit_and_reach, ", "fifty_run_time, eight_hundred_run_time, ",
			"one_thousand_run_time, one_minute_sit_up, ", "pull_up, mark, teaching_class_no, ",
			"height_weight_score, height_weight_grade, ", "vital_capacity_score, vital_capacity_grade, ",
			"standing_long_jump_score, standing_long_jump_grade, ", "sit_and_reach_score, sit_and_reach_grade, ",
			"one_minute_sit_up_score, one_minute_sit_up_grade, ", "pull_up_score, pull_up_grade, ",
			"fifty_run_score, fifty_run_grade, ", "eight_hundred_run_score, eight_hundred_run_grade, ",
			"one_thousand_run_score, one_thousand_run_grade, ", "is_tested, is_free_test, total_score, ",
			"total_score_grade, is_pass)", "values (#{universityId,jdbcType=BIGINT}, #{schoolYear,jdbcType=VARCHAR}, ",
			"#{term,jdbcType=BIT}, #{collegeName,jdbcType=VARCHAR}, #{gradeNo,jdbcType=BIGINT}, ",
			"#{classNo,jdbcType=BIGINT}, #{className,jdbcType=VARCHAR}, ",
			"#{studentNo,jdbcType=VARCHAR}, #{nationalityNo,jdbcType=BIGINT}, ",
			"#{nationalityName,jdbcType=VARCHAR}, #{studentName,jdbcType=VARCHAR}, ",
			"#{isMan,jdbcType=BIT}, #{birthday,jdbcType=DATE}, #{homeAddress,jdbcType=VARCHAR}, ",
			"#{height,jdbcType=DECIMAL}, #{weight,jdbcType=DECIMAL}, ",
			"#{bmi,jdbcType=DECIMAL}, #{bmiScore,jdbcType=SMALLINT}, ",
			"#{bmiGrade,jdbcType=VARCHAR}, #{vitalCapacity,jdbcType=BIGINT}, ",
			"#{standingLongJump,jdbcType=INTEGER}, #{sitAndReach,jdbcType=DECIMAL}, ",
			"#{fiftyRunTime,jdbcType=DECIMAL}, #{eightHundredRunTime,jdbcType=DECIMAL}, ",
			"#{oneThousandRunTime,jdbcType=DECIMAL}, #{oneMinuteSitUp,jdbcType=SMALLINT}, ",
			"#{pullUp,jdbcType=SMALLINT}, #{mark,jdbcType=VARCHAR}, #{teachingClassNo,jdbcType=BIGINT}, ",
			"#{heightWeightScore,jdbcType=SMALLINT}, #{heightWeightGrade,jdbcType=VARCHAR}, ",
			"#{vitalCapacityScore,jdbcType=SMALLINT}, #{vitalCapacityGrade,jdbcType=VARCHAR}, ",
			"#{standingLongJumpScore,jdbcType=SMALLINT}, #{standingLongJumpGrade,jdbcType=VARCHAR}, ",
			"#{sitAndReachScore,jdbcType=SMALLINT}, #{sitAndReachGrade,jdbcType=VARCHAR}, ",
			"#{oneMinuteSitUpScore,jdbcType=SMALLINT}, #{oneMinuteSitUpGrade,jdbcType=VARCHAR}, ",
			"#{pullUpScore,jdbcType=SMALLINT}, #{pullUpGrade,jdbcType=VARCHAR}, ",
			"#{fiftyRunScore,jdbcType=SMALLINT}, #{fiftyRunGrade,jdbcType=VARCHAR}, ",
			"#{eightHundredRunScore,jdbcType=SMALLINT}, #{eightHundredRunGrade,jdbcType=VARCHAR}, ",
			"#{oneThousandRunScore,jdbcType=SMALLINT}, #{oneThousandRunGrade,jdbcType=VARCHAR}, ",
			"#{isTested,jdbcType=BIT}, #{isFreeTest,jdbcType=BIT}, #{totalScore,jdbcType=DECIMAL}, ",
			"#{totalScoreGrade,jdbcType=VARCHAR}, #{isPass,jdbcType=BIT})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(PhysicalTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_physical_test
	 * @mbg.generated  Sun Nov 26 10:54:40 CST 2017
	 */
	int insertSelective(PhysicalTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_physical_test
	 * @mbg.generated  Sun Nov 26 10:54:40 CST 2017
	 */
	List<PhysicalTest> selectByExample(PhysicalTestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_physical_test
	 * @mbg.generated  Sun Nov 26 10:54:40 CST 2017
	 */
	@Select({ "select", "id, university_id, school_year, term, college_name, grade_no, class_no, class_name, ",
			"student_no, nationality_no, nationality_name, student_name, is_man, birthday, ",
			"home_address, height, weight, bmi, bmi_score, bmi_grade, vital_capacity, standing_long_jump, ",
			"sit_and_reach, fifty_run_time, eight_hundred_run_time, one_thousand_run_time, ",
			"one_minute_sit_up, pull_up, mark, teaching_class_no, height_weight_score, height_weight_grade, ",
			"vital_capacity_score, vital_capacity_grade, standing_long_jump_score, standing_long_jump_grade, ",
			"sit_and_reach_score, sit_and_reach_grade, one_minute_sit_up_score, one_minute_sit_up_grade, ",
			"pull_up_score, pull_up_grade, fifty_run_score, fifty_run_grade, eight_hundred_run_score, ",
			"eight_hundred_run_grade, one_thousand_run_score, one_thousand_run_grade, is_tested, ",
			"is_free_test, total_score, total_score_grade, is_pass", "from wzsport_physical_test",
			"where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.wzsport.mapper.PhysicalTestMapper.BaseResultMap")
	PhysicalTest selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_physical_test
	 * @mbg.generated  Sun Nov 26 10:54:40 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PhysicalTest record, @Param("example") PhysicalTestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_physical_test
	 * @mbg.generated  Sun Nov 26 10:54:40 CST 2017
	 */
	int updateByExample(@Param("record") PhysicalTest record, @Param("example") PhysicalTestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_physical_test
	 * @mbg.generated  Sun Nov 26 10:54:40 CST 2017
	 */
	int updateByPrimaryKeySelective(PhysicalTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_physical_test
	 * @mbg.generated  Sun Nov 26 10:54:40 CST 2017
	 */
	@Update({ "update wzsport_physical_test", "set university_id = #{universityId,jdbcType=BIGINT},",
			"school_year = #{schoolYear,jdbcType=VARCHAR},", "term = #{term,jdbcType=BIT},",
			"college_name = #{collegeName,jdbcType=VARCHAR},", "grade_no = #{gradeNo,jdbcType=BIGINT},",
			"class_no = #{classNo,jdbcType=BIGINT},", "class_name = #{className,jdbcType=VARCHAR},",
			"student_no = #{studentNo,jdbcType=VARCHAR},", "nationality_no = #{nationalityNo,jdbcType=BIGINT},",
			"nationality_name = #{nationalityName,jdbcType=VARCHAR},",
			"student_name = #{studentName,jdbcType=VARCHAR},", "is_man = #{isMan,jdbcType=BIT},",
			"birthday = #{birthday,jdbcType=DATE},", "home_address = #{homeAddress,jdbcType=VARCHAR},",
			"height = #{height,jdbcType=DECIMAL},", "weight = #{weight,jdbcType=DECIMAL},",
			"bmi = #{bmi,jdbcType=DECIMAL},", "bmi_score = #{bmiScore,jdbcType=SMALLINT},",
			"bmi_grade = #{bmiGrade,jdbcType=VARCHAR},", "vital_capacity = #{vitalCapacity,jdbcType=BIGINT},",
			"standing_long_jump = #{standingLongJump,jdbcType=INTEGER},",
			"sit_and_reach = #{sitAndReach,jdbcType=DECIMAL},", "fifty_run_time = #{fiftyRunTime,jdbcType=DECIMAL},",
			"eight_hundred_run_time = #{eightHundredRunTime,jdbcType=DECIMAL},",
			"one_thousand_run_time = #{oneThousandRunTime,jdbcType=DECIMAL},",
			"one_minute_sit_up = #{oneMinuteSitUp,jdbcType=SMALLINT},", "pull_up = #{pullUp,jdbcType=SMALLINT},",
			"mark = #{mark,jdbcType=VARCHAR},", "teaching_class_no = #{teachingClassNo,jdbcType=BIGINT},",
			"height_weight_score = #{heightWeightScore,jdbcType=SMALLINT},",
			"height_weight_grade = #{heightWeightGrade,jdbcType=VARCHAR},",
			"vital_capacity_score = #{vitalCapacityScore,jdbcType=SMALLINT},",
			"vital_capacity_grade = #{vitalCapacityGrade,jdbcType=VARCHAR},",
			"standing_long_jump_score = #{standingLongJumpScore,jdbcType=SMALLINT},",
			"standing_long_jump_grade = #{standingLongJumpGrade,jdbcType=VARCHAR},",
			"sit_and_reach_score = #{sitAndReachScore,jdbcType=SMALLINT},",
			"sit_and_reach_grade = #{sitAndReachGrade,jdbcType=VARCHAR},",
			"one_minute_sit_up_score = #{oneMinuteSitUpScore,jdbcType=SMALLINT},",
			"one_minute_sit_up_grade = #{oneMinuteSitUpGrade,jdbcType=VARCHAR},",
			"pull_up_score = #{pullUpScore,jdbcType=SMALLINT},", "pull_up_grade = #{pullUpGrade,jdbcType=VARCHAR},",
			"fifty_run_score = #{fiftyRunScore,jdbcType=SMALLINT},",
			"fifty_run_grade = #{fiftyRunGrade,jdbcType=VARCHAR},",
			"eight_hundred_run_score = #{eightHundredRunScore,jdbcType=SMALLINT},",
			"eight_hundred_run_grade = #{eightHundredRunGrade,jdbcType=VARCHAR},",
			"one_thousand_run_score = #{oneThousandRunScore,jdbcType=SMALLINT},",
			"one_thousand_run_grade = #{oneThousandRunGrade,jdbcType=VARCHAR},",
			"is_tested = #{isTested,jdbcType=BIT},", "is_free_test = #{isFreeTest,jdbcType=BIT},",
			"total_score = #{totalScore,jdbcType=DECIMAL},", "total_score_grade = #{totalScoreGrade,jdbcType=VARCHAR},",
			"is_pass = #{isPass,jdbcType=BIT}", "where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(PhysicalTest record);

	@Select({ "select max(id)", "from wzsport_physical_test" })
	int getMaxId();
}