package com.wzsport.mapper;

import com.wzsport.model.StudentUserView;
import com.wzsport.model.StudentUserViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface StudentUserViewMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_user_view
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	long countByExample(StudentUserViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_user_view
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	int deleteByExample(StudentUserViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_user_view
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	@Insert({ "insert into wzsport_student_user_view (class_name, univetsity_id, ", "user_type, open_id, ",
			"student_no, is_man, student_name, ", "class_id)",
			"values (#{className,jdbcType=VARCHAR}, #{univetsityId,jdbcType=BIGINT}, ",
			"#{userType,jdbcType=TINYINT}, #{openId,jdbcType=VARCHAR}, ",
			"#{studentNo,jdbcType=VARCHAR}, #{isMan,jdbcType=BIT}, #{studentName,jdbcType=VARCHAR}, ",
			"#{classId,jdbcType=BIGINT})" })
	int insert(StudentUserView record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_user_view
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	int insertSelective(StudentUserView record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_user_view
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	List<StudentUserView> selectByExample(StudentUserViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_user_view
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	int updateByExampleSelective(@Param("record") StudentUserView record,
			@Param("example") StudentUserViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_user_view
	 * @mbg.generated  Wed Nov 15 11:00:50 CST 2017
	 */
	int updateByExample(@Param("record") StudentUserView record, @Param("example") StudentUserViewExample example);
}