package com.wzsport.mapper;

import com.wzsport.model.UpdatePhysicalTestRecord;
import com.wzsport.model.UpdatePhysicalTestRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface UpdatePhysicalTestRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_update_physical_test_record
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	long countByExample(UpdatePhysicalTestRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_update_physical_test_record
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	int deleteByExample(UpdatePhysicalTestRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_update_physical_test_record
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	@Delete({ "delete from wzsport_update_physical_test_record", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_update_physical_test_record
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	@Insert({ "insert into wzsport_update_physical_test_record (physical_test_id, alter_user_id, ",
			"alter_user_name, remarks, ", "alter_time, is_alter)",
			"values (#{physicalTestId,jdbcType=BIGINT}, #{alterUserId,jdbcType=BIGINT}, ",
			"#{alterUserName,jdbcType=VARCHAR}, #{remarks,jdbcType=VARCHAR}, ",
			"#{alterTime,jdbcType=TIMESTAMP}, #{isAlter,jdbcType=BIT})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(UpdatePhysicalTestRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_update_physical_test_record
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	int insertSelective(UpdatePhysicalTestRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_update_physical_test_record
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	List<UpdatePhysicalTestRecord> selectByExample(UpdatePhysicalTestRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_update_physical_test_record
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	@Select({ "select", "id, physical_test_id, alter_user_id, alter_user_name, remarks, alter_time, is_alter",
			"from wzsport_update_physical_test_record", "where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.wzsport.mapper.UpdatePhysicalTestRecordMapper.BaseResultMap")
	UpdatePhysicalTestRecord selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_update_physical_test_record
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	int updateByExampleSelective(@Param("record") UpdatePhysicalTestRecord record,
			@Param("example") UpdatePhysicalTestRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_update_physical_test_record
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	int updateByExample(@Param("record") UpdatePhysicalTestRecord record,
			@Param("example") UpdatePhysicalTestRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_update_physical_test_record
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	int updateByPrimaryKeySelective(UpdatePhysicalTestRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_update_physical_test_record
	 * @mbg.generated  Fri Nov 24 16:22:45 CST 2017
	 */
	@Update({ "update wzsport_update_physical_test_record", "set physical_test_id = #{physicalTestId,jdbcType=BIGINT},",
			"alter_user_id = #{alterUserId,jdbcType=BIGINT},", "alter_user_name = #{alterUserName,jdbcType=VARCHAR},",
			"remarks = #{remarks,jdbcType=VARCHAR},", "alter_time = #{alterTime,jdbcType=TIMESTAMP},",
			"is_alter = #{isAlter,jdbcType=BIT}", "where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(UpdatePhysicalTestRecord record);
}